### ISSUE TITLE
Are you planning to maintain this fork?

### ISSUE THREAD

**Issue by mcarans** [pwoolvett/flakehell#3]
I made a PR against the current flakehell (https://github.com/flakehell/flakehell) to make it work with flake8 4, but the maintainer is not responding to mine or any other issues or PRs. I saw you had made this fork and called it flakeheaven in pypi but there hasn't been much activity in this repo. Do you intend to maintain it?

**Comment by pwoolvett** [comment]
it was the original goal, see https://github.com/pwoolvett/flakehell/projects/1

i talked with both the original author and the flakehell/flakehell owner, and I think all efforts should be concentrated in a single place (wherever). It's a shame the other fork is stagnant...I was really hoping to put my efforts there

Having said that, that flakeheaven i published was enough to fulfill my requirements for work, and I dont have much time to invest.

so... to answer your question: kind of.

Regarding the governance problems, and if there are enough people interested, I could move this repo to flakeheaven/flakeheaven and include volunteers (ie you and other pr authors from flakehell/flakehell) as a steering group

**Comment by mcarans** [comment]
I agree that there should be a single place. Ideally the flakehell/flakehell owner would gracefully hand over to someone else, but at this point it seems unlikely given his unresponsiveness. Perhaps we should give him a few more days to respond to my last message ([which I sent 3 days ago](https://github.com/flakehell/flakehell/issues/25#issuecomment-997549839)) and if there is no response, go with making a flakeheaven repo with a better governance structure.

**Comment by mcarans** [comment]
@pwoolvett I have had no response from the flakehell/flakehell owner. There have however been expressions of interest in maintaining a fork in this issue: https://github.com/flakehell/flakehell/issues/25. Would you be prepared to go ahead and set up flakeheaven/flakeheaven and add those in the steering group as admins on both the repo and pypi to ensure redundancy?

**Comment by pwoolvett** [comment]
https://github.com/flakeheaven/flakeheaven/discussions/1
